### ISSUE TITLE
Testflight testing

### ISSUE THREAD

**Issue by haustraliaer** [hivewallet/hive-ios#21]
So far I've found everything to work as expected  _except_ for the account details syncing. If everyone else can test on whatever devices they have available and report back here that'd be great.

Things to check:
- create wallet
- open existing wallet
- change your details (name + email)
- scan a QR code
- find someone with waggle
- broadcast yourself from ios and find yourself on web.hivewallet.com with waggle
- send coins to your ios wallet (try refresh button)
- send coins from your ios wallet
- switch to litecoin and **try all of the above again**

**Comment by haustraliaer** [comment]
Issues to fix:
- [ ] Syncing name and email #22 
- [x] Litecoin QR response #19 
- [x] Kemp folds bug #12 

Tested so far:
- [ ] iPhone 4
- [x] iPhone 4s
- [x] iPhone 5
- [ ] iPhone 5s
- [ ] iPhone 5c
- [ ] iPad 2
- [ ] iPad 3
- [ ] iPad mini
- [x] iPad mini (retz)

**Comment by genecyber** [comment]
Can you add me to testflight? Genecyber@gmail.comUuid: FFFFFFFF6940317F59614FB2B06E5818E89B2FE2

**Comment by haustraliaer** [comment]
cc: @jsuder to add anyone who submits their details here.

Also please add my iPad Uuid, which should be on the same account.

**Comment by mackuba** [comment]
@genecyber: invite sent, please log in on the device and register it there.

In general, anyone who's interested in testing can follow this link and add their device: https://www.testflightapp.com/join/ad099163d49ec161ab0e81495ef9c84c-MzUwNjEw/

**Comment by dabura667** [comment]
matsuringo667@gmail.com

UDID: 854F71BA0C925661672AEA8856CB484428568C5E

@genecyber Where did you get your UDID, it looks like the spoofed one iOS throws at Apps that try to access it.

Plug into iTunes, then go to the main page of your iDevice, click the "Serial Number" area until it says "UDID"

If you did get it from a valid source... wow, lots of FFFFFFFF going on in your device :-D

**Comment by genecyber** [comment]
I had assumed it was padding and yes I just used an app from the app store I was in your computer of the time.

**Comment by dabura667** [comment]
@genecyber Yeah, I tried searching all over google and the only results I got were

"If it starts with a bunch of FFFFF then it's not your actual UDID"

"You can only check it with iTunes or other related products by connecting to a computer"

etc etc... I couldn't find an app that displayed it accurately... so I gave up and plugged it in.

**Comment by genecyber** [comment]
Looks like I could get my udid from the testflight site by installing the profile. 

UDID:cf9b57288e322247a69365f1708a58fbbbe8564a
